### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/home/alex/temp/temp/images'

### ISSUE THREAD

**Issue by alexlittle** [chaotic-kingdoms/OUXMLConverter#22]
I tried running the script, but am getting an error about the images directory:

> Applying XSLT to the course (100%). Done.
> Traceback (most recent call last):
>   File "ouxml/ouxml.py", line 53, in <module>
>     main(sys.argv)
>   File "ouxml/ouxml.py", line 34, in main
>     course = parser.retrieve_course()
>   File "/home/alex/data/Digital-Campus/development/openwash/OUXMLConverter/ouxml/CourseParser.py", line 45, in retrieve_course
>     cp.preprocess_course()
>   File "/home/alex/data/Digital-Campus/development/openwash/OUXMLConverter/ouxml/ContentPreprocessor.py", line 24, in preprocess_course
>     self.optimize_images()
>   File "/home/alex/data/Digital-Campus/development/openwash/OUXMLConverter/ouxml/ContentPreprocessor.py", line 57, in optimize_images
>     images = listdir(images_dir)
> OSError: [Errno 2] No such file or directory: '/home/alex/temp/temp/images'

First I'd tried running with a specified output path:

> python ouxml/ouxml.py -o /home/alex/temp/ /home/alex/temp/openwash.txt

and then without:

> python ouxml/ouxml.py /home/alex/temp/openwash.txt

I also tried creating the dir '/home/alex/temp/temp/images' - but I get the same error message each time.

**Comment by jjoseba** [comment]
I can't manage to reproduce it...
My first impression was that it could be caused by a course that contains no images, but it works well too. What are the contents of your `openwash.txt`? Is the script run by a user that could not have permissions to execute in that directory?

I'll add a try/catch anyway, and we'll see what happens

**Comment by alexlittle** [comment]
The input file I was using was:

http://www.open.edu/openlearnworks/mod/oucontent/view.php?id=79926&content=scxml
http://www.open.edu/openlearnworks/mod/oucontent/view.php?id=79927&content=scxml

However when I then removed the &content=scxml, so the file was then:

http://www.open.edu/openlearnworks/mod/oucontent/view.php?id=79926
http://www.open.edu/openlearnworks/mod/oucontent/view.php?id=79927

This then worked. I read the part about &content=scxml as being optional to remove, rather than it having to be removed!

**Comment by jjoseba** [comment]
Yes, the documentation was a bit unclear...
I've made a new commit making it work even if the `content` param is present in the input file :grin:
